// Generated by scripts/extract-mascot.py -- do not hand-edit.
//
// Where each pupil sprite sits on its pose and how far it may travel,
// all as percentages so they survive any rendered height (mascot.md §6.1).

export interface Eye {
  /** Sprite box, as a percentage of the pose's box. */
  left: number;
  top: number;
  width: number;
  height: number;
  /** The eye opening the pupil is clipped to, same units. */
  clipCx: number;
  clipCy: number;
  clipRx: number;
  clipRy: number;
  /** Travel before the pupil touches the lid, as a percentage of the sprite. */
  travelX: number;
  travelY: number;
}

export const RESTING_EYES: Eye[] = [
  /* near */ { left: 55.639, top: 25.915, width: 7.519, height: 7.317, clipCx: 58.271, clipCy: 29.421, clipRx: 3.308, clipRy: 2.409, travelX: 15.500, travelY: 0.000 },
  /* far */ { left: 71.429, top: 23.171, width: 6.015, height: 5.793, clipCx: 73.872, clipCy: 25.854, clipRx: 2.406, clipRy: 1.829, travelX: 15.000, travelY: 1.053 },
];

